# refData/Codes/main_gemini.py
import json
import requests
import io
from typing import List, Optional
from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse, HTMLResponse
from pydantic import BaseModel
from openai import OpenAI
from pptx import Presentation
from pptx.util import Inches

# ==========================================
# 1. 設定區域
# ==========================================
app = FastAPI(title="AI PPT Generator")

# 設定 LLM (請確保您的 Ollama 正在運行)
client = OpenAI(
    base_url="http://localhost:11434/v1",
    api_key="ollama",
)
MODEL_NAME = "gpt-oss:20b"  # 或您本地實際的模型名稱

# 定義請求資料模型
class TopicRequest(BaseModel):
    topic: str

# ==========================================
# 2. 核心邏輯函數 (從之前的腳本改寫)
# ==========================================

def get_llm_content(topic: str):
    """呼叫 LLM 取得 JSON 結構"""
    print(f"[Backend] 正在分析主題: {topic}")
    system_prompt = """
    你是一個專業簡報設計師。請根據主題生成 JSON 格式的簡報大綱 (繁體中文)。
    JSON 結構必須包含：
    {
        "title": "大標題",
        "slides": [
            {
                "title": "頁面標題",
                "content": ["重點1", "重點2"],
                "image_query": "英文圖片搜尋關鍵字"
            }
        ]
    }
    請只回傳 JSON，不要包含 Markdown 格式。
    """

    try:
        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"主題：{topic}。請製作 3 頁簡報。"},
            ],
            temperature=0.7,
        )
        content = response.choices[0].message.content
        # 清理字串，確保 JSON 可解析
        content = content.replace("```json", "").replace("```", "").strip()
        return json.loads(content)
    except Exception as e:
        print(f"[Error] LLM 處理失敗: {e}")
        raise HTTPException(status_code=500, detail="LLM 生成失敗，請檢查 Ollama 是否開啟。")

def download_image_stream(keyword: str):
    """下載圖片並回傳 BytesIO 物件"""
    try:
        # 使用 Lorem Picsum 模擬圖片搜尋
        # 在正式版請換成 Unsplash API
        url = f"https://picsum.photos/800/600?random={hash(keyword)}"
        res = requests.get(url, timeout=5)
        if res.status_code == 200:
            return io.BytesIO(res.content)
    except Exception as e:
        print(f"[Warning] 圖片下載失敗 ({keyword}): {e}")
    return None

def generate_pptx_binary(data: dict) -> io.BytesIO:
    """在記憶體中生成 PPT 並回傳 Binary Stream"""
    prs = Presentation()

    # 1. 封面
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = data.get("title", "AI Presentation")
    slide.placeholders[1].text = "Generated by FastAPI & Python-pptx"

    # 2. 內容頁
    bullet_layout = prs.slide_layouts[1]

    for slide_data in data.get("slides", []):
        slide = prs.slides.add_slide(bullet_layout)
        shapes = slide.shapes

        # 標題
        shapes.title.text = slide_data.get("title", "")

        # 調整文字框 (左半邊)
        body_shape = shapes.placeholders[1]
        body_shape.width = Inches(5.0)
        body_shape.left = Inches(0.5)

        tf = body_shape.text_frame
        tf.word_wrap = True
        for point in slide_data.get("content", []):
            p = tf.add_paragraph()
            p.text = point
            p.level = 0

        # 插入圖片 (右半邊)
        img_query = slide_data.get("image_query")
        if img_query:
            img_stream = download_image_stream(img_query)
            if img_stream:
                try:
                    shapes.add_picture(
                        img_stream,
                        left=Inches(5.8),
                        top=Inches(2.0),
                        height=Inches(3.5)
                    )
                except Exception as e:
                    print(f"[Error] 插入圖片失敗: {e}")

    # 關鍵：儲存到 BytesIO 而不是磁碟
    output = io.BytesIO()
    prs.save(output)
    output.seek(0) # 指標歸零，準備讀取
    return output

# ==========================================
# 3. FastAPI 路由
# ==========================================

@app.get("/", response_class=HTMLResponse)
async def read_root():
    """回傳簡單的前端介面"""
    return """
    <!DOCTYPE html>
    <html>
    <head>
        <title>AI PPT Generator</title>
        <style>
            body { font-family: sans-serif; max-width: 600px; margin: 50px auto; padding: 20px; }
            h1 { color: #333; }
            input[type="text"] { width: 100%; padding: 10px; font-size: 16px; margin-bottom: 10px; }
            button { background-color: #007bff; color: white; padding: 10px 20px; border: none; cursor: pointer; font-size: 16px; }
            button:hover { background-color: #0056b3; }
            button:disabled { background-color: #ccc; }
            #status { margin-top: 20px; color: #666; }
            .loader { border: 4px solid #f3f3f3; border-top: 4px solid #3498db; border-radius: 50%; width: 20px; height: 20px; animation: spin 2s linear infinite; display: none; vertical-align: middle; margin-left: 10px;}
            @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
        </style>
    </head>
    <body>
        <h1>✨ AI 自動生成 PPT</h1>
        <p>輸入您想要的主題，AI 將為您撰寫大綱並自動配圖。</p>

        <input type="text" id="topicInput" placeholder="例如：綠色能源的未來發展" />
        <button onclick="generatePPT()" id="genBtn">
            開始生成 <span class="loader" id="loader"></span>
        </button>

        <div id="status"></div>

        <script>
            async function generatePPT() {
                const topic = document.getElementById('topicInput').value;
                if (!topic) { alert("請輸入主題！"); return; }

                const btn = document.getElementById('genBtn');
                const loader = document.getElementById('loader');
                const status = document.getElementById('status');

                // UI 狀態切換
                btn.disabled = true;
                loader.style.display = "inline-block";
                status.innerText = "🧠 AI 正在思考架構並搜尋圖片，請稍候 (約需 10-30 秒)...";

                try {
                    const response = await fetch('/generate', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({ topic: topic })
                    });

                    if (!response.ok) throw new Error("生成失敗");

                    // 處理檔案下載
                    const blob = await response.blob();
                    const url = window.URL.createObjectURL(blob);
                    const a = document.createElement('a');
                    a.href = url;
                    a.download = `${topic}_presentation.pptx`;
                    document.body.appendChild(a);
                    a.click();
                    document.body.removeChild(a);

                    status.innerText = "✅ 下載完成！";
                } catch (error) {
                    console.error(error);
                    status.innerText = "❌ 發生錯誤，請檢查後端是否正常運作。";
                } finally {
                    btn.disabled = false;
                    loader.style.display = "none";
                }
            }
        </script>
    </body>
    </html>
    """

@app.post("/generate")
async def generate_ppt_endpoint(request: TopicRequest):
    """API 端點：接收主題 -> 生成 -> 回傳檔案"""

    # 1. 取得 AI 文字內容
    ppt_data = get_llm_content(request.topic)

    # 2. 轉換為 PPT 二進位流
    ppt_stream = generate_pptx_binary(ppt_data)

    # 3. 回傳串流 (瀏覽器會視為檔案下載)
    filename = f"AI_Gen_{request.topic}.pptx"
    # 使用 quote 處理中文檔名 (雖然現代瀏覽器通常很聰明，但最好標準化)
    from urllib.parse import quote
    filename_encoded = quote(filename)

    return StreamingResponse(
        ppt_stream,
        media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
        headers={
            "Content-Disposition": f"attachment; filename*=UTF-8''{filename_encoded}"
        }
    )

if __name__ == "__main__":
    import uvicorn
    # 啟動伺服器
    uvicorn.run(app, host="0.0.0.0", port=8000)
